apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: capstone-easypay
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    project: capstone
  type: LoadBalancer
status:
  loadBalancer: {}
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    project: capstone
  name: capstone-easypay
spec:
  replicas: 2 
  selector:
    matchLabels:
      project: capstone
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        project: capstone
    spec:
      containers:
      - name: capstone-easypay
        image: docker.io/smaqsoodi/capstone-project-easypay:latest
      # Just spin & wait forever to avoic CrashloopBack
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]

        ports:
        - containerPort: 80      
        resources:
          requests:
            cpu: "200m"
status: {}

