apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: capstone-easypay
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: capstone-easypay
  targetCPUUtilizationPercentage: 50
#  metrics:
#  - type: Resource
#    resources:
#      name: cpu
#      targetAverageUtilization: 50
status:
  currentReplicas: 0
  desiredReplicas: 0
                                                            
