--- 
- 
  connection: local
  gather_facts: false
  hosts: localhost
  tasks: 
    - 
      block: 
        - 
          ec2_instance_facts: 
            aws_access_key: "{{ec2_access_key}}"
            aws_secret_key: "{{ec2_secret_key}}"
            region: "{{ region }}"
          name: "Get instances facts"
          register: result
        - 
          debug: 
            msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
          loop: "{{ result.instances }}"
          name: "Instances ID"
      name: Facts
      tags: always
    - 
      block: 
        - 
          ec2_key: 
            aws_access_key: "{{ec2_access_key}}"
            aws_secret_key: "{{ec2_secret_key}}"
            key_material: "{{ lookup('file', '/Users/julianosilva/.ssh/{{ key_name }}.pub') }}"
            name: "{{ key_name }}"
            region: "{{ region }}"
          name: "Upload public key to AWS"
        - 
          ec2_group: 
            aws_access_key: "{{ec2_access_key}}"
            aws_secret_key: "{{ec2_secret_key}}"
            description: "Sec group for app {{ id }}"
            name: "{{ sec_group }}"
            region: "{{ region }}"
            rules: 
              - 
                cidr_ip: 0.0.0.0/0
                ports: 
                  - 22
                proto: tcp
                rule_desc: "allow all on ssh port"
          name: "Create security group"
          register: result_sec_group
        - 
          ec2: 
            aws_access_key: "{{ec2_access_key}}"
            aws_secret_key: "{{ec2_secret_key}}"
            count: 1
            group_id: "{{ result_sec_group.group_id }}"
            id: "{{ id }}"
            image: "{{ image }}"
            instance_type: t2.micro
            key_name: "{{ key_name }}"
            region: "{{ region }}"
            wait: true
          name: "Provision instance(s)"
      name: "Provisioning EC2 instances"
      tags: 
        - never
        - create_ec2
  vars: 
    id: web-app
    image: ami-0f93b5fd8f220e428
    key_name: my_aws
    region: us-east-2
    sec_group: "{{ id }}-sec"
