apiVersion: v1
kind: Pod
metadata:
  name: test-capstone
  labels:
    project: capstone
spec:
  containers:
  - name: mycontainer
    image: docker.io/httpd
    ports:
    - containerPort: 80
                                                                    
